variables:
  k8s_coreos_stable_box_url: https://storage.googleapis.com/stable.release.core-os.net/amd64-usr/current/coreos_production_vagrant.json
  k8s_coreos_alpha_box_url: https://storage.googleapis.com/alpha.release.core-os.net/amd64-usr/current/coreos_production_vagrant.json
  k8s_coreos_beta_box_url: https://storage.googleapis.com/beta.release.core-os.net/amd64-usr/current/coreos_production_vagrant.json


teracy-dev-certs:
  ca:
    pkcs1_generated: true # to generate the PKCS#1 *-ca.key from the *-ca-key.pem file
  cert:
    generated: false

# k8s config backport from kubespray https://github.com/kubernetes-incubator/kubespray/blob/master/Vagrantfile#L26
teracy-dev-k8s:
  # configurable here
  kubespray:
    lookup_path: extensions # relative to the Vagrantfile
    location:
      git:
        remote:
          origin: https://github.com/kubernetes-sigs/kubespray.git
        branch: v2.9.0 # v2.10.0 is buggy https://github.com/kubernetes-sigs/kubespray/issues/4695
  ansible:
    verbose: v
    mode: guest # or host to run ansible from the host instead of from the guest
    playbook_path: cluster.yml # relative within the kubespray repo or /cluster.yml is relative to the Vagrantfile when appending / at the beginning as convention
    # you can add any host_vars here with key-value to override inventory
    version: 2.7.10 # kubespray is buggy on ansible 2.8: https://github.com/kubernetes-sigs/kubespray/issues/3985
    host_vars:
      flannel_interface: "eth1"
      kube_network_plugin: flannel
      kube_network_plugin_multus: "False"
      docker_keepcache: "1"
      download_localhost: "False"
      download_run_once: "False"
      kubeconfig_localhost: "True"
      kubectl_localhost: "True"
      disable_ipv6_dns: "True"
      kube_proxy_mode: iptables
      kube_service_addresses: 10.96.0.0/16
      kube_pods_subnet: 10.244.0.0/16
      # Directory where credentials will be stored
      # moved out of inventory_dir to avoid host unreachable problem
      credentials_dir: "/vagrant/workspace/credentials"
    # added @since v0.4.0
    extra_vars:
      ansible_become_pass: "vagrant"

  num_instances: 1
  instance_name_prefix: "k8s"
  vm_gui: false
  vm_memory: 2048
  vm_cpus: 2
  os: ubuntu # must match one of the _id from supported_oses
  supported_oses:
    # ubuntu
    - _id: ubuntu
      box: bento/ubuntu-18.04
      user: vagrant
    # coreos
    - _id: coreos-stable
      box: coreos-stable
      user: core
      box_url: "%{k8s_coreos_stable_box_url}"
    - _id: coreos-alpha
      box: coreos-alpha
      user: core
      box_url: "%{k8s_coreos_alpha_box_url}"
    - _id: coreos-beta
      box: coreos-beta
      user: core
      box_url: "%{k8s_coreos_beta_box_url}"
    # centos
    - _id: centos
      box: centos/7
      user: vagrant
    # opensuse
    - _id: opensuse
      box: opensuse/openSUSE-42.3-x86_64
      user: vagrant
    - _id: opensuse-tumbleweed
      box: opensuse/openSUSE-Tumbleweed-x86_64
      user: vagrant
    # fedora
    - _id: fedora
      box: fedora/28-cloud-base
      user: vagrant

  network:
    type: "private_network" # TODO: support "public_network" with automatic public ip of the master node so it's LAN accessible
    subnet: 172.17.8

  # don't try to change node_template if you don't know what you're going to do
  # node template to be overriden
  node_template:
    _id:
    name:
    vm:
      box:
      box_version:
      box_url:
      networks:
        - _id: "0"
          type:
          ip:
    ssh:
      insert_key: false
      username:
    providers:
      - _id: "0"
        gui:
        memory:
        cpus:
        description: "k8s #{Time.now.getutc.to_i}"
